<a href="https://colab.research.google.com/github/manjotmb20/fastai-v3/blob/master/ensemble2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from numpy import linalg as LA

dataset=pd.read_csv('train.csv')

dataset2=pd.read_csv('test.csv')
dataset=dataset.fillna(dataset.mean())
dataset2=dataset2.fillna(dataset2.mean())
embarked=pd.get_dummies(dataset.Embarked,prefix='Embarked')
embarked2=pd.get_dummies(dataset2.Embarked,prefix='Embarked')
dataset=pd.concat([dataset,embarked],axis=1)
dataset2=pd.concat([dataset2,embarked2],axis=1)
dataset.drop(['Cabin', 'Ticket','Embarked','Name','PassengerId'],axis=1, inplace=True)
dataset2.drop(['Cabin', 'Ticket','Embarked','Name','PassengerId'],axis=1, inplace=True)
lc=LabelEncoder()
dataset[['Sex']]=lc.fit_transform(dataset[['Sex']])
dataset2[['Sex']]=lc.transform(dataset2[['Sex']])
sc=StandardScaler()
dataset[['Fare']]=sc.fit_transform(dataset[['Fare']])
dataset2[['Fare']]=sc.transform(dataset2[['Fare']])
sc1=StandardScaler()
dataset[['Age']]=sc1.fit_transform(dataset[['Age']])
dataset2[['Age']]=sc1.transform(dataset2[['Age']])
df_test=dataset['Survived']
df_train=dataset.drop('Survived',axis=1)
test=dataset2

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_auc_score,accuracy_score
x_train,x_val,y_train,y_val=train_test_split(df_train,df_test,test_size=0.2,random_state=9)
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)
ypred=classifier.predict(x_val)
print(roc_auc_score(y_val,ypred))
print(accuracy_score(y_val,ypred))
df=pd.DataFrame()
df['pred']=ypred

classifier1=DecisionTreeClassifier()
classifier1.fit(x_train,y_train)
ypred1=classifier1.predict(x_val)
df['pred2']=ypred1
print(roc_auc_score(y_val,ypred1))
print(accuracy_score(y_val,ypred1))

survived=pd.get_dummies(df.pred,prefix='Survived')
survived_classifier2=pd.get_dummies(df.pred2,prefix='Survsecond')
df=pd.concat([df,survived],axis=1)
df=pd.concat([df,survived_classifier2],axis=1)
df.drop(['pred','pred2'],axis=1,inplace=True)

0.7627848101265823
0.776536312849162
0.7391139240506329
0.7486033519553073


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [0]:
mem_mat=df

In [76]:
mem_mat

Survived_0  Survived_1  Survsecond_0  Survsecond_1
0             1           0             1             0
1             1           0             1             0
2             1           0             1             0
3             1           0             1             0
4             0           1             0             1
..          ...         ...           ...           ...
174           0           1             0             1
175           0           1             0             1
176           1           0             1             0
177           0           1             0             1
178           0           1             0             1

[179 rows x 4 columns]

In [0]:
cor_mat=mem_mat.dot(mem_mat.T)

In [7]:
cor_mat

0    1    2    3    4    5    6    ...  172  173  174  175  176  177  178
0      2    2    2    2    0    2    1  ...    0    0    0    0    2    0    0
1      2    2    2    2    0    2    1  ...    0    0    0    0    2    0    0
2      2    2    2    2    0    2    1  ...    0    0    0    0    2    0    0
3      2    2    2    2    0    2    1  ...    0    0    0    0    2    0    0
4      0    0    0    0    2    0    1  ...    2    2    2    2    0    2    2
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
174    0    0    0    0    2    0    1  ...    2    2    2    2    0    2    2
175    0    0    0    0    2    0    1  ...    2    2    2    2    0    2    2
176    2    2    2    2    0    2    1  ...    0    0    0    0    2    0    0
177    0    0    0    0    2    0    1  ...    2    2    2    2    0    2    2
178    0    0    0    0    2    0    1  ...    2    2    2    2    0    2    2

[179 rows x 179 columns]

In [0]:
y_prob=classifier.predict_proba(x_val)
y_prob2=classifier1.predict_proba(x_val)

In [0]:
objclass_mat1=pd.DataFrame(y_prob,columns=['Survived','NotSurvived'])
objclass_mat2=pd.DataFrame(y_prob2,columns=['Survived','NotSurvived'])

In [69]:
'''objclass_mat1=pd.concat([objclass_mat2],axis=1)'''
objclass_mat1
Fo=np.array(objclass_mat1)
Fo

array([[0.6525206 , 0.3474794 ],
       [0.93185302, 0.06814698],
       [0.9413454 , 0.0586546 ],
       [0.83590434, 0.16409566],
       [0.48319562, 0.51680438],
       [0.85924218, 0.14075782],
       [0.6301185 , 0.3698815 ],
       [0.90050361, 0.09949639],
       [0.65604109, 0.34395891],
       [0.55977349, 0.44022651],
       [0.8700973 , 0.1299027 ],
       [0.42511281, 0.57488719],
       [0.89073315, 0.10926685],
       [0.89864843, 0.10135157],
       [0.06696136, 0.93303864],
       [0.86539778, 0.13460222],
       [0.82504985, 0.17495015],
       [0.31829387, 0.68170613],
       [0.2422165 , 0.7577835 ],
       [0.81683772, 0.18316228],
       [0.80544908, 0.19455092],
       [0.74780945, 0.25219055],
       [0.29899564, 0.70100436],
       [0.85510366, 0.14489634],
       [0.83850766, 0.16149234],
       [0.59050059, 0.40949941],
       [0.90054759, 0.09945241],
       [0.9084539 , 0.0915461 ],
       [0.90054759, 0.09945241],
       [0.16581695, 0.83418305],
       [0.

In [0]:
gpclass_mat=pd.DataFrame(columns=['Survived','NotSurvived'],index=['class1surv','class1notsurv','class2surv','class2notsurv'])

In [43]:
prob1s=np.sum(objclass_mat1.Survived)/len(objclass_mat1)
prob1ns=np.sum(objclass_mat1.NotSurvived)/len(objclass_mat1)
prob2s=np.sum(objclass_mat2.Survived)/len(objclass_mat2)
prob2ns=np.sum(objclass_mat2.NotSurvived)/len(objclass_mat2)
prob1s

0.604096834264432

In [0]:
list1=[]
list1.append(prob1s)
list1.append(prob1ns)
list1.append(prob2s)
list1.append(prob2ns)

list2=[]
list2.append(prob1ns)
list2.append(prob1s)
list2.append(prob2ns)
list2.append(prob2s)
gpclass_mat['Survived']=list1
gpclass_mat['NotSurvived']=list2



In [80]:
gpclass_mat
Fg=np.array(gpclass_mat)
Fg

array([[0.60409683, 0.39590317],
       [0.39590317, 0.60409683],
       [0.60409683, 0.39590317],
       [0.39590317, 0.60409683]])

In [0]:
kmshape=mem_mat.shape
kcshape=cor_mat.shape

In [84]:
Yg=np.zeros(shape=gpclass_mat.shape)
thres=0.5
for i in range(Fg.shape[0]):
  for j in range(Fg.shape[1]):
    if Fg[i][j]>thres:
      Yg[i][j]=1
Yg      

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [15]:
kcshape

(179, 179)

In [0]:
import sys
threshold=sys.float_info.epsilon

In [35]:
Km=np.zeros(shape=kmshape)
Kc=np.zeros(shape=kcshape)
Khm=np.array(mem_mat)
Khc=np.array(cor_mat)
Km=Khm
d=np.zeros(shape=(kmshape[0]))
for i in range(kmshape[0]):
  d[i]=np.sum(Km[i],axis=0)

Km=Km/d.reshape((d.shape[0],1))


Km

array([[0.5, 0. , 0.5, 0. ],
       [0.5, 0. , 0.5, 0. ],
       [0.5, 0. , 0.5, 0. ],
       [0.5, 0. , 0.5, 0. ],
       [0. , 0.5, 0. , 0.5],
       [0.5, 0. , 0.5, 0. ],
       [0.5, 0. , 0. , 0.5],
       [0.5, 0. , 0.5, 0. ],
       [0.5, 0. , 0. , 0.5],
       [0.5, 0. , 0. , 0.5],
       [0.5, 0. , 0.5, 0. ],
       [0. , 0.5, 0.5, 0. ],
       [0.5, 0. , 0.5, 0. ],
       [0.5, 0. , 0.5, 0. ],
       [0. , 0.5, 0. , 0.5],
       [0.5, 0. , 0. , 0.5],
       [0.5, 0. , 0. , 0.5],
       [0. , 0.5, 0. , 0.5],
       [0. , 0.5, 0. , 0.5],
       [0.5, 0. , 0.5, 0. ],
       [0.5, 0. , 0.5, 0. ],
       [0.5, 0. , 0.5, 0. ],
       [0. , 0.5, 0.5, 0. ],
       [0.5, 0. , 0.5, 0. ],
       [0.5, 0. , 0.5, 0. ],
       [0.5, 0. , 0. , 0.5],
       [0.5, 0. , 0.5, 0. ],
       [0.5, 0. , 0.5, 0. ],
       [0.5, 0. , 0.5, 0. ],
       [0. , 0.5, 0. , 0.5],
       [0.5, 0. , 0.5, 0. ],
       [0.5, 0. , 0.5, 0. ],
       [0. , 0.5, 0. , 0.5],
       [0. , 0.5, 0. , 0.5],
       [0.5, 0

In [0]:
Kc=np.zeros(shape=kcshape)
Khc=np.array(cor_mat)
Kc=Khc
d=np.zeros(shape=(kcshape[0]))
for i in range(kcshape[0]):
  d[i]=np.sum(Kc[i],axis=0)
  
Kc=Kc/d.reshape((d.shape[0],1))

In [37]:
Kc

array([[0.00888889, 0.00888889, 0.00888889, ..., 0.00888889, 0.        ,
        0.        ],
       [0.00888889, 0.00888889, 0.00888889, ..., 0.00888889, 0.        ,
        0.        ],
       [0.00888889, 0.00888889, 0.00888889, ..., 0.00888889, 0.        ,
        0.        ],
       ...,
       [0.00888889, 0.00888889, 0.00888889, ..., 0.00888889, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.01503759,
        0.01503759],
       [0.        , 0.        , 0.        , ..., 0.        , 0.01503759,
        0.01503759]])

In [70]:
Fo.shape

(179, 2)

In [0]:
J1=0
for i in range(Khm.shape[0]):
  for j in range(Khm.shape[1]):
    J1=J1+Khm[i][j]*(np.linalg.norm((Fo[i]-Fg[j]), ord=2)**2)
J2=0
for i in range(Khc.shape[0]):
  for j in range(Khc.shape[1]):
    J2=J2+Khc[i][j]*(np.linalg.norm((Fo[i]-Fo[j]), ord=2)**2)    
J3=0
for i in range(Khc.shape[0]):
  J3=J3+(np.linalg.norm((Fo[i]-Yo[i]), ord=2)**2) 

J4=0
for i in range(Khm.shape[1]):
  J4=J4+(np.linalg.norm((Fg[i]-Yg[i]), ord=2)**2) 




In [87]:
print(J1)
print(J2)
print(J3)
print(J4)


43.63890860216581
4502.249461118704
21.621095648707477
1.253914533115557


Ye dekhna

In [78]:
df2=pd.DataFrame()
df2['Survived']=mem_mat['Survived_0']
df2['NonSurvived']=mem_mat['Survived_1']
Yo=np.array(df2)
Yo

array([[1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0,

In [32]:
a=np.empty(shape=(2,4))
a[0][1]=0.71
a[1][1]=0.2
c=np.zeros(shape=(2))
for i in range(2):
  c[i]=np.sum(a[i],axis=0)

print(c)
print(a)
final=a/c.reshape((c.shape[0],1))
print(final)

[1.29479532 1.03333333]
[[0.21809069 0.71       0.36670463 0.        ]
 [0.3299193  0.2        0.50341403 0.        ]]
[[0.16843642 0.54834922 0.28321436 0.        ]
 [0.31927675 0.19354839 0.48717487 0.        ]]
